name: Next.js build and deploy to s3
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Node management
        uses: actions/setup-node@v3
        with:
          node-version: "20.7.0"

      - name: Install packages
        run: |
          node --version
          npm install -g pnpm
          pnpm --version
          pnpm install

      - name: Build static files
        run: |
          pnpm run build
