name: Next.js build and deploy to S3

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Node management
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
      - name: Install packages and build
        run: |
          node --version
          npm -v
          npm install .
          npm run build
